# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ff684e33b4371ff7774aca2c5b87d46185e013c665ce4bb6c6f3f354340c725bab4eb86e00181f2cb4f9486f12076ff4efdc540d6a98102e6b327830c9476ef

test:
  secret_key_base: 4eb52bca40c7510ae41284a979da4245cdd8b8fd163e069e094727d8c95b86827da63ee035b718d7e3834adad7859799256081b1c242f07b8727b31af204daec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
